<?php
/**
 * DO NOT EDIT: PAGE GENERATED BY CLASS.AUTOLOAD
 */
namespace seago\devtools;

$pathToAutoload = "../lib/lib.autoload/src/autoload.php";

// Register custom autoload function for current namespace
spl_autoload_register(__NAMESPACE__."\__autoload");

/**
 * __autoload Function
 * Magic function that is kicked off when an undefined object is created.
 * Instantiates class autoload to search for and include desired class definition.
 *
 * @access	public
 * @param	string	$class	Name of class to be instantiated
 * @return	void
 */
function __autoload($class) {
	global $pathToAutoload;
	require_once($pathToAutoload);
	$load = new autoload(substr($class,strlen(__NAMESPACE__)+1));
	require_once($load->path);
}